# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Gradle Build and Cypress Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.1
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle and run unit tests
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: Paketito
        path: build/libs
        retention-days: 5
    - name: Run app in background
      run: java -jar build/libs/henlofren-0.0.1-SNAPSHOT.jar &
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run cypress tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        headless: true

